services:
  sub2api:
    image: sub2api-local:latest
    build:
      context: ..
      dockerfile: Dockerfile

  sub2api-b:
    image: sub2api-local:latest
    build:
      context: ..
      dockerfile: Dockerfile
